<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class NewsSeeder extends Seeder {
    public function run(): void {
        DB::table('news')->insert([
            'title' => 'Nieuwe trainingstijden 1',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid rerum ut, dolorum mollitia, asperiores ex accusamus, quas porro laudantium cupiditate eius quidem minima placeat. Quo, suscipit eligendi deleniti quibusdam dolores sapiente? Laudantium facilis facere ipsam omnis, nulla ab. Laboriosam hic aperiam vero unde error ipsam quam cupiditate, dolorem quidem nesciunt non eveniet voluptates mollitia soluta nulla incidunt veniam! Repudiandae iure odit blanditiis temporibus explicabo eaque inventore! Necessitatibus nam magnam nihil eaque maxime eum adipisci officia suscipit dolorum debitis quisquam eligendi, alias, ullam, repellendus totam fuga minima ut inventore! Quia vitae doloremque necessitatibus quod corrupti ipsa voluptatem quas, cumque, consequuntur dignissimos et. Consequuntur unde sequi dolor dolorum ipsa nam illum magni. Praesentium hic doloremque qui commodi neque. Odio fugit libero aspernatur ratione quisquam excepturi sapiente dolorem, aperiam doloribus quasi quidem optio fugiat consectetur delectus enim! Nemo doloribus reiciendis consequuntur ipsa tempore suscipit eligendi atque perspiciatis veniam velit beatae dolore neque, doloremque dolorem, at natus placeat. Quasi dolores repellat recusandae saepe culpa, fuga harum error quos eveniet! Cum laudantium at officiis? Debitis adipisci numquam doloribus obcaecati atque eveniet error tempore maxime incidunt dignissimos eaque odio ab fugiat quaerat commodi pariatur eligendi consequuntur, quas, excepturi magnam nostrum vero. Officia dolorem consequatur beatae fugiat.',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('news')->insert([
            'title' => 'Nieuwe trainingstijden 2',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid rerum ut, dolorum mollitia, asperiores ex accusamus, quas porro laudantium cupiditate eius quidem minima placeat. Quo, suscipit eligendi deleniti quibusdam dolores sapiente? Laudantium facilis facere ipsam omnis, nulla ab. Laboriosam hic aperiam vero unde error ipsam quam cupiditate, dolorem quidem nesciunt non eveniet voluptates mollitia soluta nulla incidunt veniam! Repudiandae iure odit blanditiis temporibus explicabo eaque inventore! Necessitatibus nam magnam nihil eaque maxime eum adipisci officia suscipit dolorum debitis quisquam eligendi, alias, ullam, repellendus totam fuga minima ut inventore! Quia vitae doloremque necessitatibus quod corrupti ipsa voluptatem quas, cumque, consequuntur dignissimos et. Consequuntur unde sequi dolor dolorum ipsa nam illum magni. Praesentium hic doloremque qui commodi neque. Odio fugit libero aspernatur ratione quisquam excepturi sapiente dolorem, aperiam doloribus quasi quidem optio fugiat consectetur delectus enim! Nemo doloribus reiciendis consequuntur ipsa tempore suscipit eligendi atque perspiciatis veniam velit beatae dolore neque, doloremque dolorem, at natus placeat. Quasi dolores repellat recusandae saepe culpa, fuga harum error quos eveniet! Cum laudantium at officiis? Debitis adipisci numquam doloribus obcaecati atque eveniet error tempore maxime incidunt dignissimos eaque odio ab fugiat quaerat commodi pariatur eligendi consequuntur, quas, excepturi magnam nostrum vero. Officia dolorem consequatur beatae fugiat.',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('news')->insert([
            'title' => 'Nieuwe trainingstijden 3',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid rerum ut, dolorum mollitia, asperiores ex accusamus, quas porro laudantium cupiditate eius quidem minima placeat. Quo, suscipit eligendi deleniti quibusdam dolores sapiente? Laudantium facilis facere ipsam omnis, nulla ab. Laboriosam hic aperiam vero unde error ipsam quam cupiditate, dolorem quidem nesciunt non eveniet voluptates mollitia soluta nulla incidunt veniam! Repudiandae iure odit blanditiis temporibus explicabo eaque inventore! Necessitatibus nam magnam nihil eaque maxime eum adipisci officia suscipit dolorum debitis quisquam eligendi, alias, ullam, repellendus totam fuga minima ut inventore! Quia vitae doloremque necessitatibus quod corrupti ipsa voluptatem quas, cumque, consequuntur dignissimos et. Consequuntur unde sequi dolor dolorum ipsa nam illum magni. Praesentium hic doloremque qui commodi neque. Odio fugit libero aspernatur ratione quisquam excepturi sapiente dolorem, aperiam doloribus quasi quidem optio fugiat consectetur delectus enim! Nemo doloribus reiciendis consequuntur ipsa tempore suscipit eligendi atque perspiciatis veniam velit beatae dolore neque, doloremque dolorem, at natus placeat. Quasi dolores repellat recusandae saepe culpa, fuga harum error quos eveniet! Cum laudantium at officiis? Debitis adipisci numquam doloribus obcaecati atque eveniet error tempore maxime incidunt dignissimos eaque odio ab fugiat quaerat commodi pariatur eligendi consequuntur, quas, excepturi magnam nostrum vero. Officia dolorem consequatur beatae fugiat.',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('news')->insert([
            'title' => 'Nieuwe trainingstijden 4',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid rerum ut, dolorum mollitia, asperiores ex accusamus, quas porro laudantium cupiditate eius quidem minima placeat. Quo, suscipit eligendi deleniti quibusdam dolores sapiente? Laudantium facilis facere ipsam omnis, nulla ab. Laboriosam hic aperiam vero unde error ipsam quam cupiditate, dolorem quidem nesciunt non eveniet voluptates mollitia soluta nulla incidunt veniam! Repudiandae iure odit blanditiis temporibus explicabo eaque inventore! Necessitatibus nam magnam nihil eaque maxime eum adipisci officia suscipit dolorum debitis quisquam eligendi, alias, ullam, repellendus totam fuga minima ut inventore! Quia vitae doloremque necessitatibus quod corrupti ipsa voluptatem quas, cumque, consequuntur dignissimos et. Consequuntur unde sequi dolor dolorum ipsa nam illum magni. Praesentium hic doloremque qui commodi neque. Odio fugit libero aspernatur ratione quisquam excepturi sapiente dolorem, aperiam doloribus quasi quidem optio fugiat consectetur delectus enim! Nemo doloribus reiciendis consequuntur ipsa tempore suscipit eligendi atque perspiciatis veniam velit beatae dolore neque, doloremque dolorem, at natus placeat. Quasi dolores repellat recusandae saepe culpa, fuga harum error quos eveniet! Cum laudantium at officiis? Debitis adipisci numquam doloribus obcaecati atque eveniet error tempore maxime incidunt dignissimos eaque odio ab fugiat quaerat commodi pariatur eligendi consequuntur, quas, excepturi magnam nostrum vero. Officia dolorem consequatur beatae fugiat.',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('news')->insert([
            'title' => 'Nieuwe trainingstijden 5',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid rerum ut, dolorum mollitia, asperiores ex accusamus, quas porro laudantium cupiditate eius quidem minima placeat. Quo, suscipit eligendi deleniti quibusdam dolores sapiente? Laudantium facilis facere ipsam omnis, nulla ab. Laboriosam hic aperiam vero unde error ipsam quam cupiditate, dolorem quidem nesciunt non eveniet voluptates mollitia soluta nulla incidunt veniam! Repudiandae iure odit blanditiis temporibus explicabo eaque inventore! Necessitatibus nam magnam nihil eaque maxime eum adipisci officia suscipit dolorum debitis quisquam eligendi, alias, ullam, repellendus totam fuga minima ut inventore! Quia vitae doloremque necessitatibus quod corrupti ipsa voluptatem quas, cumque, consequuntur dignissimos et. Consequuntur unde sequi dolor dolorum ipsa nam illum magni. Praesentium hic doloremque qui commodi neque. Odio fugit libero aspernatur ratione quisquam excepturi sapiente dolorem, aperiam doloribus quasi quidem optio fugiat consectetur delectus enim! Nemo doloribus reiciendis consequuntur ipsa tempore suscipit eligendi atque perspiciatis veniam velit beatae dolore neque, doloremque dolorem, at natus placeat. Quasi dolores repellat recusandae saepe culpa, fuga harum error quos eveniet! Cum laudantium at officiis? Debitis adipisci numquam doloribus obcaecati atque eveniet error tempore maxime incidunt dignissimos eaque odio ab fugiat quaerat commodi pariatur eligendi consequuntur, quas, excepturi magnam nostrum vero. Officia dolorem consequatur beatae fugiat.',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
